# -*- mode: ruby -*-
# vi: set ft=ruby :

project_name = "TestProject"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 4000, host: 4000
  config.vm.provision "shell", inline: <<-SHELL
    set -x
    mkdir -p /home/vagrant/#{project_name.downcase}
    cd /home/vagrant/#{project_name.downcase}
    echo "~~ Setup Node"
    curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -
    apt-get install -y nodejs
    npm install npm -g
    echo "~~ Setup Erlang/Elixir"
    wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb && sudo dpkg -i erlang-solutions_1.0_all.deb
    apt-get update
    apt-get -y install esl-erlang
    apt-get -y install elixir
    mix local.hex --force
    echo "~~ Setup Postgres"
    apt-get -y install postgresql
    sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
    echo "~~ Setup Phoenix"
    mix archive.install https://github.com/phoenixframework/phoenix/releases/download/v1.1.2/phoenix_new-1.1.2.ez --force
    mix phoenix.new /home/vagrant/#{project_name.downcase} --force
    mix deps.get
    mix local.rebar
    npm install -g brunch
    rm -rf node_modules
    npm cache clean
    npm install
    mix ecto.create
    mix phoenix.server
  SHELL
end
