# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/precise64"

  config.vm.network "private_network", ip: "192.168.30.30"

  config.vm.provision "shell",
    inline: "dpkg -i /vagrant/chef*.deb"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "chef-repo/cookbooks"
    chef.json = JSON.parse( IO.read("chef-repo/web.json") )#"chef-repo/web.json"
    #chef.add_recipe "apt"
    #chef.add_recipe "phpapp"
  end

end
